name: Samping Professional

on:
  schedule:
    # Mengubah dari setiap jam ('0 * * * *') menjadi setiap 5 menit
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    
    container:
      image: mcr.microsoft.com/playwright/python:v1.58.0-jammy

    steps:
      - name: 🔐 Checkout Logic
        uses: actions/checkout@v4
        with:
          repository: Khofah567765/kolamikan 
          token: ${{ secrets.PAT_TOKEN }}
          path: private_vip_1
          
      - name: 📦 Install Python Libraries
        run: |
          pip install firebase-admin playwright==1.58.0

      - name: 🚀 Run Scraper & Push Firebase
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          STRIP_ID: ${{ secrets.STRIP_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          python private_vip_1/samping.py
