name: Samping Professional

on:
  schedule:
    - cron: '0 * * * *' # Jalan otomatis setiap jam
  workflow_dispatch: # Bisa dijalankan manual dari tab Actions

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    
    # MENGGUNAKAN CONTAINER: Mematikan proses download dependency Ubuntu yang lama
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-noble

    steps:
      - name: 🔐 Checkout Logic (Repo Private)
        uses: actions/checkout@v4
        with:
          repository: Khofah567765/kolamikan 
          token: ${{ secrets.PAT_TOKEN }}
          path: private_vip_1
          
      - name: 📦 Install Python Libraries
        run: |
          pip install firebase-admin playwright
          # Tidak perlu install-deps lagi karena sudah ada di dalam container mcr

      - name: 🚀 Run Scraper & Push Firebase
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          STRIP_ID: ${{ secrets.STRIP_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          # Langsung jalankan script dari folder path yang sudah ditentukan
          python private_vip_1/samping.py
