name: Samping Professional

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest
    
    # PERBAIKAN: Menggunakan tag jammy yang sudah pasti ada
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy

    steps:
      - name: 🔐 Checkout Logic
        uses: actions/checkout@v4
        with:
          repository: Khofah567765/kolamikan 
          token: ${{ secrets.PAT_TOKEN }}
          path: private_vip_1
          
      - name: 📦 Install Python Libraries
        run: |
          pip install firebase-admin playwright

      - name: 🚀 Run Scraper & Push Firebase
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          STRIP_ID: ${{ secrets.STRIP_ID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: |
          python private_vip_1/samping.py
